services:
  postgres:
    restart: always
    image: postgres:latest
    command: "-d 1"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  ws:
    image: ghcr.io/izrin96/objekt-explorer-websocket:latest
    build:
      context: .
      dockerfile: ./docker/ws.Dockerfile
    restart: always
    environment:
      - DB_PROXY_URL
      - DB_PROXY_KEY
      - INDEXER_PROXY_URL
      - INDEXER_PROXY_KEY
    ports:
      - "8081:3000"
  browserless:
    image: ghcr.io/browserless/chromium
    ports:
      - "9222:3000"
    environment:
      - TOKEN=your-token-here
  web:
    image: ghcr.io/izrin96/objekt-explorer-web:latest
    build:
      args:
        INDEXER_PROXY_KEY: ${INDEXER_PROXY_KEY}
        INDEXER_PROXY_URL: ${INDEXER_PROXY_URL}
        DB_PROXY_KEY: ${DB_PROXY_KEY}
        DB_PROXY_URL: ${DB_PROXY_URL}
        NEXT_PUBLIC_UMAMI_SCRIPT_URL: ${NEXT_PUBLIC_UMAMI_SCRIPT_URL}
        NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${NEXT_PUBLIC_UMAMI_WEBSITE_ID}
        NEXT_PUBLIC_ACTIVITY_WEBSOCKET_URL: ${NEXT_PUBLIC_ACTIVITY_WEBSOCKET_URL}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
        DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
        BROWSER_CDP_URL: ${BROWSER_CDP_URL}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        DATABASE_URL: ${DATABASE_URL}
        S3_ENDPOINT: ${S3_ENDPOINT}
        S3_PORT: ${S3_PORT}
        S3_ACCESS_KEY: ${S3_ACCESS_KEY}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
        S3_USE_SSL: ${S3_USE_SSL}
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - INDEXER_PROXY_KEY
      - INDEXER_PROXY_URL
      - DB_PROXY_KEY
      - DB_PROXY_URL
      - NEXT_PUBLIC_UMAMI_SCRIPT_URL
      - NEXT_PUBLIC_UMAMI_WEBSITE_ID
      - NEXT_PUBLIC_ACTIVITY_WEBSOCKET_URL
      - BETTER_AUTH_SECRET
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - BROWSER_CDP_URL
      - NEXT_PUBLIC_SITE_URL
      - DATABASE_URL
      - S3_ENDPOINT
      - S3_PORT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_USE_SSL
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  db_data:
  minio_data:
