services:
  postgres:
    restart: always
    image: postgres:latest
    command: '-d 1'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  proxy:
    image: ghcr.io/izrin96/objekt-explorer-proxy:latest
    build:
      context: .
      dockerfile: ./docker/proxy.Dockerfile
    restart: always
    environment:
      - PROXY_HOST=postgres
      - PROXY_USER=postgres
      - PROXY_NAME=main
      - PROXY_PASS=postgres
      - PROXY_PORT=5432
      - PROXY_HTTP_PORT=8080
      - PROXY_KEY=key
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  ws:
    image: ghcr.io/izrin96/objekt-explorer-websocket:latest
    build:
      context: .
      dockerfile: ./docker/ws.Dockerfile
    restart: always
    environment:
      - DB_PROXY_URL
      - DB_PROXY_KEY
      - INDEXER_PROXY_URL
      - INDEXER_PROXY_KEY
    ports:
      - "8081:3000"
  browserless:
    image: ghcr.io/browserless/chromium
    ports:
      - "9222:3000"
    environment:
      - TOKEN=your-token-here
  # chromium:
  #   image: docker.io/chromedp/headless-shell:latest
  #   ports:
  #     - "9222:9222"
  #   command:
  #     - --remote-debugging-auth-token=your-token-here
  web:
    image: ghcr.io/izrin96/objekt-explorer-web:latest
    build:
      args:
        INDEXER_PROXY_KEY: ${INDEXER_PROXY_KEY}
        INDEXER_PROXY_URL: ${INDEXER_PROXY_URL}
        DB_PROXY_KEY: ${DB_PROXY_KEY}
        DB_PROXY_URL: ${DB_PROXY_URL}
        NEXT_PUBLIC_UMAMI_SCRIPT_URL: ${NEXT_PUBLIC_UMAMI_SCRIPT_URL}
        NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${NEXT_PUBLIC_UMAMI_WEBSITE_ID}
        NEXT_PUBLIC_ACTIVITY_WEBSOCKET_URL: ${NEXT_PUBLIC_ACTIVITY_WEBSOCKET_URL}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
        DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
        BROWSER_CDP_URL: ${BROWSER_CDP_URL}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - INDEXER_PROXY_KEY
      - INDEXER_PROXY_URL
      - DB_PROXY_KEY
      - DB_PROXY_URL
      - NEXT_PUBLIC_UMAMI_SCRIPT_URL
      - NEXT_PUBLIC_UMAMI_WEBSITE_ID
      - NEXT_PUBLIC_ACTIVITY_WEBSOCKET_URL
      - BETTER_AUTH_SECRET
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - BROWSER_CDP_URL
      - NEXT_PUBLIC_SITE_URL
volumes:
  db_data: